version: '3.1'

networks:
  corp:
    driver: bridge

services:
  api:
    networks:
      - corp
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "3333:3333"
  app:
    networks:
      - corp
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - "4200:4200"
  db:
    image: postgres
    restart: always
    networks:
      - corp
    environment:
      POSTGRES_PASSWORD: example
  go-backend:
    networks:
      - corp
    build:
      context: ./apps/go-backend
    ports:
      - "50051:50051"
